### ISSUE TITLE
Color in chat, for ranges

### ISSUE THREAD

**Issue by MrEigo** [ryandw11/UltraChat#16]
How do I make each range have a different color in the chat?

**Comment by ryandw11** [comment]
At the bottom of the config.yml there is the following settings:
```yml
##############################################
#                   Range                    #
##############################################
#The global channel which everyone can see.
#All of these formats support Components. See Normal Chat for an example.
Global:
    format: '&6[Global]&r %prefix% %player% %suffix% &7>>'
World:
    format: '&d[World]&r %prefix% %player% %suffix% &7>>'
Local:
    format: '&b[Local]&r %prefix% %player% %suffix% &7>>'
    range: 100
```
Just add a color code after the `>>`
Example:
```yml
##############################################
#                   Range                    #
##############################################
#The global channel which everyone can see.
#All of these formats support Components. See Normal Chat for an example.
Global:
    format: '&6[Global]&r %prefix% %player% %suffix% &7>>&b'
World:
    format: '&d[World]&r %prefix% %player% %suffix% &7>>&c'
Local:
    format: '&b[Local]&r %prefix% %player% %suffix% &7>>&d'
    range: 100
```
